name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Flutter build and deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Say start a build
      run: echo flutter build web
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - name: Run a flutter build and deploy
      run: |
        flutter config --enable-web
        flutter pub get
        flutter build web
    - name: Copy build dir
      run: cp -r ./build/web/* ./
      working-directory: ./

